# Generated by Django 5.2.6 on 2025-11-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('employment_status', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Retired', 'Retired'), ('Self-employed', 'Self-employed'), ('Student', 'Student')], max_length=20)),
                ('occupation', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Education', 'Education'), ('Sales', 'Sales'), ('Service', 'Service'), ('Skilled Trades', 'Skilled Trades'), ('Tech', 'Tech')], max_length=20)),
                ('education', models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=20)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('has_children', models.BooleanField(default=False)),
                ('monthly_income_sgd', models.FloatField(blank=True, null=True)),
                ('preferred_category', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
