# Generated by Django 5.2.6 on 2025-11-14 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestorefront', '0004_paymentinformation_shippinginformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinformation',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='onlinestorefront.customer'),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='expiry_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='expiry_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='payment_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='shippings', to='onlinestorefront.customer'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
