# Generated by Django 5.2.6 on 2025-11-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestorefront', '0005_remove_paymentinformation_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='billing_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_last4',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='cardholder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_month',
            field=models.PositiveIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_year',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
