# Generated by Django 5.2.6 on 2025-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestorefront', '0006_order_billing_address_order_card_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='postal_code',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
