# Generated by Django 5.2.6 on 2025-11-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestorefront', '0007_alter_shippinginformation_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
