# Generated by Django 5.2.6 on 2025-11-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestorefront', '0008_alter_paymentinformation_expiry_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinformation',
            name='payment_token',
        ),
    ]
