# Generated by Django 5.2.6 on 2025-11-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestorefront', '0009_remove_paymentinformation_payment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
