# Generated by Django 5.2.6 on 2025-11-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestorefront', '0010_alter_paymentinformation_expiry_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='contact_number',
            field=models.CharField(max_length=8),
        ),
    ]
