# Generated by Django 5.2.6 on 2025-10-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_code", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
                ("product_category", models.CharField(max_length=255)),
                ("product_subcategory", models.CharField(max_length=255)),
                ("quantity_on_hand", models.IntegerField()),
                ("unit_price", models.FloatField()),
            ],
        ),
    ]
