# Generated by Django 5.2.6 on 2025-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                ("total_amount", models.FloatField()),
                ("customer_name", models.CharField(max_length=255)),
            ],
        ),
    ]
